name: build production

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3
            - run: docker build -t com-javierhardman:nginx -f Dockerfile .
            - run: docker-compose --env-file /home/docker/.env up -d
